### ISSUE TITLE
Switching from oxcal to calibrator

### ISSUE THREAD

**Issue by MartinHinz** [xronos-ch/xronos.rails#182]
Removing the reliance on Oxcal has been a goal from the beginning. I have created a first (working) draft under the branch [using_calibrator](/xronos-ch/xronos.rails/tree/using_calibrator). @joeroe, would be very interested in your opinion. Might as well solve #149 and #150 in the process?

**Comment by joeroe** [comment]
Great! Yes, it would definitely be good to drop OxCal. If nothing else, I assume this is faster? Switching to vega is also very satisfying and already fits much better into the UI.

Some suggestions based on the first draft:

1. Yes I think we should make this a stimulus controller (#150) rather than attaching it to the window application-wide. I'm fairly sure that if we do this and write an appropriate `disconnect()` method (see https://www.betterstimulus.com/integrating-libraries/lifecycle.html) this will fix #149.
2. Instead of having to have OS-specific binaries in this repository and switch between them, can we just expect `calibrator` being in the system PATH (or an env variable) and configure it to build in the docker containers?
3. Is there any way we can set styles for vega (e.g. fonts) from global CSS instead of hard-coding them in javascript?

**Comment by joeroe** [comment]
Actually, re. that first one, I noticed that the https://github.com/ankane/vega-ruby readme says:

> You can also use Vega directly. In this case, you don’t need to include Vega-Lite in the JavaScript files.

**Comment by MartinHinz** [comment]
I think that means something else: When you are using Vega (not Vega.lite), than you do not need to use vega-lite. But what is currently in the application.js is

`window.vegaEmbed = require("vega-embed").default`

so this refers to vega-embed. Does this make sense?

See also here: https://github.com/ankane/vega-ruby/blob/04d35b5e5893763331aa2f36791ae6314f6d5910/lib/vega.rb#L18

**Comment by MartinHinz** [comment]
Also also, Vega is already compatible with turbo links, afaik.

**Comment by joeroe** [comment]
I can't reproduce #149 in your branch so yes, seems so! Presumably because it uses a canvas element rather than attaching anything to the DOM via JS (so no need for a tear-down after all). Very nice.

But as, far as I understand it, there is still an advantage of making a simply controller that does `window.vegaEmbed = require("vega-embed").default`, so that the vega JS is only loaded on pages that need it (and for consistency with other JS).

**Comment by MartinHinz** [comment]
Would love if you could use this as an educational example to introduce to me how this works in Stimulus!?
