### ISSUE TITLE
Server Logs: HTTP_BAD_GATEWAY.html.var

### ISSUE THREAD

**Issue by MartinHinz** [xronos-ch/xronos.rails#200]
In production.log, we have many:

```
I, [2023-02-04T23:39:06.764906 #121]  INFO -- : [e1e372af-66de-4373-87e0-47bc5344ae24] Started GET "/error/HTTP_BAD_GATEWAY.html.var" for 185.191.171.26 at 2023-02-04 23:39:06 +0000
F, [2023-02-04T23:39:06.765445 #121] FATAL -- : [e1e372af-66de-4373-87e0-47bc5344ae24]   
[e1e372af-66de-4373-87e0-47bc5344ae24] ActionController::RoutingError (No route matches [GET] "/error/HTTP_BAD_GATEWAY.html.var"):
```

**Comment by joeroe** [comment]
I'm at a loss with this one. The RoutingError is because Apache asks for an error page that isn't there. But Apache is asking for an error page because it didn't get a response from Rails. The corresponding Apache logs look like this:

```
Thu Feb 09 13:37:41.246987 2023] [proxy_http:error] [pid 2928790] (104)Connection reset by peer: [client 185.191.171.39:33128] AH01102: error reading status line from remote server localhost:4000
[Thu Feb 09 13:37:41.247019 2023] [proxy:error] [pid 2928790] [client 185.191.171.39:33128] AH00898: Error reading from remote server returned by /typos/132264
[Thu Feb 09 13:37:41.247306 2023] [proxy_http:error] [pid 2928790] (104)Connection reset by peer: [client 185.191.171.39:33128] AH01102: error reading status line from remote server localhost:4000
[Thu Feb 09 13:37:41.247318 2023] [proxy:error] [pid 2928790] [client 185.191.171.39:33128] AH00898: Error reading from remote server returned by /error/HTTP_BAD_GATEWAY.html.var
```

But I can't find any pattern in which requests raise it. They seem to come in large batches, during which the server is completely unresponsive. @MartinHinz does the hosting provider have any metrics where you could see if the server was overloaded around e.g. 12.30 today?

**Comment by MartinHinz** [comment]
I believe this issue is more of a symptom than the root cause of the crashes. When inspecting the server (and while doing that, emptied the production log that was 12 GB), I realize that these crashes seem to occur approximately once every 10 days. Given that this issue stems directly from the server crashing — causing Apache to fail in receiving a response from Rails — I suggest we close this issue as it is not the underlying problem. @joeroe, do you agree?
