### ISSUE TITLE
Add calibrator make instructions to README

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#323]
Needed in a dev environment anyway. Not sure about Docker?

**Comment by MartinHinz** [comment]
Added documentation, you might like to check or close this issue.

**Comment by MartinHinz** [comment]
Actually, as we have discussed this, I have outsourced the calibrator to its own docker container, so that we can use it as an API. You can find this repo here: https://github.com/xronos-ch/calibrator_api. But also, since you have developed such a fine tool like Ruby radiocarbon, maybe it also makes sense to switch to this? Depends on the speed!

**Comment by joeroe** [comment]
Either could work and would simplify deployment, but since this works, I guess it's not a big priority.
